server:
  port: 8083

spring:
  application:
    name: CONFIG-SERVER

cloud:
  config:
    server:
      git:
        uri: https://github.com/sumitMultani/config-server/tree/main
        clone-on-start: true